version: "3.1"
services:
    db:
        image: mysql
        restart: always
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ingenieriadb
            MYSQL_PASSWORD: widowmaker
            MYSQL_ROOT_PASSWORD: widowmaker 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        restart: always
        build: .
        ports: 
            - "80:80"
        volumes:
            - ../backup/server/webApplications:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: widowmaker
            MYSQL_ROOT_PASSWORD: widowmaker
volumes:
    persistent:
